# YOLOv5 🚀 by Ultralytics, GPL-3.0 license
# COCO128 dataset https://www.kaggle.com/ultralytics/coco128 (first 128 images from COCO train2017) by Ultralytics
# Example usage: python train.py --data coco128.yaml
# parent
# ├── yolov5
# └── datasets
#     └── coco128  ← downloads here (7 MB)

# "c:\users\bobgreen\documents\pythonscripts\python_envs\yolov5env\scripts\python.exe"  "C:\Users\BobGreen\Documents\PythonScripts\python_envs\yolov5env\Scripts\tensorboard.exe" --logdir runs\train_among

# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: ./  # dataset root dir
train: /content/drive/MyDrive/VisEdu - IA/Treino Teste/train  # train images (relative to 'path') 128 images
val: /content/drive/MyDrive/VisEdu - IA/Treino Teste/val  # val images (relative to 'path') 128 images
test:  # test images (optional)

# Classes
names:
  0: dormindo
  1: prestando_atencao
  2: mexendo_no_celular
  3: copiando
  4: disperso
  5: trabalho_em_grupo

  # "c:\users\bobgreen\documents\pythonscripts\python_envs\yolov5env\scripts\python.exe"  "C:\Users\BobGreen\Documents\PythonScripts\python_envs\yolov5env\Scripts\tensorboard.exe" --logdir runs\train_among